name: apex_sc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.3
  pinput: ^5.0.0
  numeric_keyboard: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets: 
  - assets/
  - assets/images/
  - assets/animations/
  - assets/icons/